## Docs
* https://dev.mysql.com/doc/
* https://docs.sqlalchemy.org/en/20/core/engines.html#mysql
* https://jupyter-tutorial.readthedocs.io/en/stable/data-processing/postgresql/ipython-sql.html
* [6.1 Tutorial: Raise Employee's Salary Using a Buffered Cursor](https://dev.mysql.com/doc/connector-python/en/connector-python-tutorial-cursorbuffered.html)

## Ref
* https://towardsdatascience.com/jupyter-magics-with-sql-921370099589

In [1]:
import db

## enviroment

In [2]:
_, mysql_user, _, mysql_password, _, _, database = db.load_env()

### Windows 関数

In [3]:
# init
%load_ext sql
%config SqlMagic.displaycon=False 
%config SqlMagic.autopandas=True

# IP addresses are variable.　: http://localhost:8888/lab?#%F0%9F%97%92-NOTE
host_ = '172.19.0.2'
%sql mysql+pymysql://{mysql_user}:{mysql_password}@{host_}/{database}

#### table_schema

In [ ]:
%%sql result_set << 
SELECT table_name, table_schema, table_type
FROM information_schema.tables
WHERE table_schema = 'Chinook'
ORDER BY table_name ASC;

11 rows affected.
Returning data to local variable result_set

In [ ]:
result_set

       table_name table_schema  table_type
0           Album      Chinook  BASE TABLE
1          Artist      Chinook  BASE TABLE
2        Customer      Chinook  BASE TABLE
3        Employee      Chinook  BASE TABLE
4           Genre      Chinook  BASE TABLE
5         Invoice      Chinook  BASE TABLE
6     InvoiceLine      Chinook  BASE TABLE
7       MediaType      Chinook  BASE TABLE
8        Playlist      Chinook  BASE TABLE
9   PlaylistTrack      Chinook  BASE TABLE
10          Track      Chinook  BASE TABLE

In [8]:
%%sql result_set <<
SELECT * FROM
Album LEFT JSON Artist
ON Album.ArtistId = Artist.ArtistId;

(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON Artist\nON Album.ArtistId = Artist.ArtistId' at line 2")
[SQL: SELECT * FROM
Album LEFT JSON Artist
ON Album.ArtistId = Artist.ArtistId;]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [7]:
result_set

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

In [53]:
%%sql result_set << 
SELECT
  Name
  , AlbumId
  , Composer
  , Milliseconds
  , Bytes
  -- , MediaTypeId
  , COUNT(Composer) AS composer_num
  -- AVG(Bytes) OVER (PARTITION BY MediaTypeId)
FROM Track
WHERE MediaTypeId = 1
-- AND composer_num > 10
GROUP BY Composer
ORDER BY composer_num DESC;

772 rows affected.
Returning data to local variable result_set

In [54]:
result_set

,Name,AlbumId,Composer,Milliseconds,Bytes,composer_num
0,The Number Of The Beast,95,Steve Harris,294635,4718897,80
1,Zoo Station,232,U2,276349,9056902,44
2,Heart Of Stone,216,Jagger/Richards,164493,5329538,35
3,Lucky 13,201,Billy Corgan,189387,6200617,31
4,Intro,163,Kurt Cobain,52218,1688527,26
...,...,...,...,...,...,...
767,Para Lennon E McCartney,158,"Lô Borges, Márcio Borges, Fernando Brant",321828,10626920,1
768,South Bound Saurez,130,John Paul Jones & Robert Plant,254406,8420427,1
769,Astronomy,35,A.Bouchard/J.Bouchard/S.Pearlman,397531,13065612,1
770,Speak To Me/Breathe,183,"Mason/Waters, Gilmour, Wright",234213,7631305,1
771,Desafinado,8,None,185338,5990473,0

In [82]:
%%sql result_set << 
SELECT
  *
FROM Track;

3503 rows affected.
Returning data to local variable result_set

In [83]:
result_set

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,None,342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
...,...,...,...,...,...,...,...,...,...
3498,3499,Pini Di Roma (Pinien Von Rom) I Pini Della Vi...,343,2,24,None,286741,4718950,0.99
3499,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",344,2,24,Franz Schubert,139200,2283131,0.99
3500,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",345,2,24,Claudio Monteverdi,66639,1189062,0.99
3501,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,2,24,Wolfgang Amadeus Mozart,221331,3665114,0.99
3502,3503,Koyaanisqatsi,347,2,10,Philip Glass,206005,3305164,0.99

In [31]:
%%sql result_set << 
select current_schema();

(pymysql.err.OperationalError) (1305, 'FUNCTION Chinook.current_schema does not exist')
[SQL: select current_schema();]
(Background on this error at: https://sqlalche.me/e/14/e3q8)